services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
    volumes:
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports:
      - 8081:80
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    
    
    
  