version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - 8081:80
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    
    
    
  