apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-trigger
  template:
    metadata:
      labels:
        app: backup-trigger
    spec:
      containers:
        - name: backup-trigger
          image: henriquepina/backup-trigger:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: backup-volume
              mountPath: /backup
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    echo "⏳ Disparando Job do Kibana Index Pattern..."
                    cp /app/kibana-indexpattern-job.yml /tmp/kibana-indexpattern-job.yml
                    sed -i "s/name: create-kibana-indexpattern/name: kibana-indexpattern-job-$(date +%s)/" /tmp/kibana-indexpattern-job.yml
                    kubectl apply -f /tmp/kibana-indexpattern-job.yml || true
      volumes:
        - name: backup-volume
          persistentVolumeClaim:
            claimName: mysql-backup-pvc
