apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-trigger-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-trigger-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: backup-trigger-role
  apiGroup: rbac.authorization.k8s.io
