apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: mysql:5.7
          command: ["sh", "-c"]
          args:
            - >
              sleep 20 &&
              mysql -h mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS usuarios_db;" &&
              mysql -h mysql -u root -proot -D usuarios_db -e "
                CREATE TABLE IF NOT EXISTS usuarios (
                  id INT AUTO_INCREMENT PRIMARY KEY,
                  nome VARCHAR(100),
                  email VARCHAR(100)
                );"

      restartPolicy: Never
