apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: backup-volume
              mountPath: /backup
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    echo "[PostStart] Aguardando MySQL ficar pronto..."
                    for i in $(seq 1 60); do
                      mysqladmin ping -h 127.0.0.1 -uroot -proot --silent && break
                      echo "[Tentativa $i] Aguardando..."
                      sleep 2
                    done
                    echo "[PostStart] Restaurando banco..."
                    mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS usuarios_db;"
                    mysql -h 127.0.0.1 -uroot -proot usuarios_db < /backup/usuarios_dump.sql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc-final
        - name: backup-volume
          persistentVolumeClaim:
            claimName: mysql-backup-pvc
