apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc-final
        - name: backup-volume
          persistentVolumeClaim:
            claimName: mysql-backup-pvc
      initContainers:
        - name: restore-db
          image: mysql:5.7
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "[Init] Verificando se o banco já foi restaurado..."
              if [ -f /var/lib/mysql/usuarios_db.flag ]; then
                echo "[Init] Banco já restaurado. Pulando restauração."
                exit 0
              fi

              echo "[Init] Esperando o MySQL iniciar..."
              for i in $(seq 1 60); do
                mysqladmin ping -h localhost --silent && break
                echo "[Tentativa $i] Aguardando MySQL subir..."
                sleep 2
              done

              echo "[Init] Criando banco e restaurando dump..."
              mysql -h localhost -u root -proot -e "CREATE DATABASE IF NOT EXISTS usuarios_db;"
              mysql -h localhost -u root -proot usuarios_db < /backup/usuarios_dump.sql

              echo "[Init] Marca de restauração criada."
              touch /var/lib/mysql/usuarios_db.flag
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: backup-volume
              mountPath: /backup
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: backup-volume
              mountPath: /backup
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ -d "/var/lib/mysql/mysql" ]; then
                echo "⚠️ Dados já existem. Pulando inicialização."
                exec mysqld
              else
                echo "📦 Inicializando banco de dados pela primeira vez..."
                exec docker-entrypoint.sh mysqld
              fi
