apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-final
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
