apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: backup-volume
              mountPath: /backup
      initContainers:
        - name: restore-db
          image: mysql:5.7
          command:
            [
              "sh",
              "-c",
              "for i in $(seq 1 60); do \
                echo \"[Tentativa $i] Aguardando MySQL subir...\"; \
                if mysqladmin ping -h 127.0.0.1 --silent; then \
                  echo 'MySQL está disponível! Restaurando dump...'; \
                  if [ -f /backup/usuarios_dump.sql ]; then \
                    mysql -h 127.0.0.1 -u root -proot < /backup/usuarios_dump.sql && break; \
                  else \
                    echo 'Nenhum dump encontrado.' && break; \
                  fi; \
                fi; \
                sleep 5; \
              done"
            ]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: backup-volume
              mountPath: /backup
      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: backup-volume
          persistentVolumeClaim:
            claimName: mysql-backup-pvc
