apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: wait-and-restore
          image: mysql:5.7
          command:
            - sh
            - -c
            - |
              set -e
              echo "[+] Verificando necessidade de restauração..."

              # Verifica se o dump da tabela já foi restaurado
              if [ ! -f /var/lib/mysql/usuarios_db/usuarios.ibd ]; then
                echo "[!] Dump ainda não restaurado. Iniciando restauração..."

                # Limpa qualquer conteúdo antigo
                rm -rf /var/lib/mysql/*
                mysqld --initialize-insecure --datadir=/var/lib/mysql

                echo "[+] Iniciando MySQL temporário para restaurar dump..."
                mysqld --skip-networking --datadir=/var/lib/mysql &

                for i in {1..10}; do
                  sleep 2
                  mysqladmin ping -uroot && break
                done

                echo "[+] Criando banco de dados..."
                mysql -uroot -e "CREATE DATABASE IF NOT EXISTS usuarios_db"

                echo "[+] Executando restauração do dump no banco usuarios_db..."
                mysql -uroot usuarios_db < /backup/usuarios_dump.sql

                echo "[✔] Finalizando MySQL temporário..."
                mysqladmin shutdown -uroot
              else
                echo "[✔] Dump já restaurado. Pulando."
              fi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: backup
              mountPath: /backup

        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /var/lib/mysql"]
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: backup
          persistentVolumeClaim:
            claimName: mysql-backup-pvc
