apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-dump
data:
  usuarios_dump.sql: |
    CREATE DATABASE IF NOT EXISTS usuarios_db;
    USE usuarios_db;

    CREATE TABLE IF NOT EXISTS usuarios (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nome VARCHAR(255),
        email VARCHAR(255)
    );
