apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-clean2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
