apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
