apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-clean
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile