apiVersion: batch/v1
kind: Job
metadata:
  name: create-kibana-indexpattern
spec:
  template:
    spec:
      containers:
        - name: create-indexpattern
          image: curlimages/curl:8.2.1
          command:
            - sh
            - -c
            - |
              echo "⏳ Esperando Kibana..."
              until curl -s http://kibana:5601 > /dev/null; do sleep 5; done
              echo "📡 Verificando se o index pattern já existe..."
              EXISTS=$(curl -s http://kibana:5601/api/saved_objects/index-pattern/php-logs | grep -c "php-logs")
              if [ "$EXISTS" -eq 0 ]; then
                echo "🆕 Criando index pattern php-logs"
                curl -s -X POST http://kibana:5601/api/saved_objects/index-pattern \
                  -H "kbn-xsrf: true" \
                  -H "Content-Type: application/json" \
                  -d '{"attributes":{"title":"php-logs","timeFieldName":"@timestamp"}}'
              else
                echo "✅ Index pattern já existe"
              fi
      restartPolicy: OnFailure
