apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-backup-job
spec:
  template:
    spec:
      containers:
        - name: backup
          image: mysql:5.7
          command: ["sh", "-c", "mysqldump -h mysql -u root -proot usuarios_db > /backup/usuarios_dump.sql"]
          volumeMounts:
            - name: backup-volume
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: backup-volume
          persistentVolumeClaim:
            claimName: mysql-backup-pvc
